name: deploy-vwanandhub
concurrency: vwan-uks

on:
  push:
    branches:
      - main
    

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: rg-vwantest-man-uks-1
  ENVIRONMENT_TYPE: Production

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: az bicep build --file Vwan/main.bicep

  validate:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        scope: resourcegroup
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./Vwan/main.bicep
        parameters: ./Vwan/UKS/vwan-uks.bicepparam.json
        deploymentMode: Validate

  preview:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Run what-if
      with:
        scope: resourcegroup
        failOnStdErr: false
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./Vwan/main.bicep
        parameters: ./Vwan/UKS/vwan-uks.bicepparam.json
        additionalArguments: --what-if

  deploy-Vwan:
    runs-on: ubuntu-latest
    needs: preview
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      id: deploy-Vwan
      name: Deploy Vwan
      with:
        scope: resourcegroup
        failOnStdErr: false
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./Vwan/main.bicep
        parameters: ./Vwan/UKS/vwan-uks.bicepparam.json
  
  deploy-Vhub-uks:
    runs-on: ubuntu-latest
    needs: deploy-Vwan
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      id: deploy-Vhub-uks
      name: Deploy Vhub UKS
      with:
              scope: resourcegroup
              failOnStdErr: false
              deploymentName: ${{ github.run_number }}
              resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
              template: ./Vhub/main.bicep
              parameters: ./Vhub/UKS/vhub-uks.bicepparam.json
  
  deploy-Vhub-ukw:
    runs-on: ubuntu-latest
    needs: deploy-Vwan
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      id: deploy-Vhub-ukw
      name: Deploy Vhub UKW
      with:
              scope: resourcegroup
              failOnStdErr: false
              deploymentName: ${{ github.run_number }}
              resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
              template: ./Vhub/main.bicep
              parameters: ./Vhub/UKW/vhub-ukw.bicepparam.json
      
        
